@startuml

participant "Client Http"
participant UserController
participant CommandProcessor

"Client Http"-> UserController : { "firstName" : "John", \n "lastName" : "DOE",\n "birthDate" : "01/01/2006"}

UserController->UserController : json valide
UserController->CommandProcessor : CreateUser
CommandProcessor -> CommandProcessor:  - 10 ans
CommandProcessor -> UserController : -\/(TooYoungError)
UserController -> "Client Http" : Reponse 400  \n {"error" : "user_too_young"}

@enduml