@startuml

participant "Client Http"
participant JobController
participant CommandProcessor
participant EventHandler


"Client Http"-> JobController : POST /api/v1/jobs {\n "askerId" : "user-543bec57400000400011f40f",  \n  "title" : "Tondre la pelouse", \n  "skill" : "Jardinnage" \n}

JobController->JobController : Missing field "expirationDate"
JobController -> "Client Http" : Reponse 400  \n {"error" : "obj.expirationDate.required"}

@enduml