@startuml

participant "Client Http"
participant JobController
participant CommandProcessor

"Client Http"-> JobController : POST /api/v1/jobs {\n "askerId" : "user-543bec57400000400011f40f",  \n  "title" : "Tondre la pelouse", \n  "skill" : "Jardinnage",\n "expirationDate"  : "01/02/2015"}

JobController->JobController : json valide
JobController->CommandProcessor : CreateJob(...)
CommandProcessor -> CommandProcessor:  expired date
CommandProcessor -> JobController : -\/(ExpiredDateError)
JobController -> JobController : ValidationError2HttpCode
JobController -> "Client Http" : Reponse 400  \n {"error" : "obj.expirationDate.invalid"}

@enduml